services:
  dev:
    image: ${DOCKER_IMAGE:-yagich/dev-tools-container:latest}
    build: .
    container_name: devstation
    hostname: devstation
    restart: unless-stopped
    ports:
      - "${SSH_PORT:-2222}:22"
    volumes:
      - ${HOME_DIR:-./data/home}:/home
      - ${WIREGUARD_DIR:-./data/wireguard}:/etc/wireguard
      - /tmp/tmux-1001:/tmp/tmux-1001
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    devices:
      - /dev/net/tun:/dev/net/tun
